version: '3'
services:
  db:
    image: postgres
  backend:
    build: .
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - LOCAL=1
      - CLASSES_APP_ID=${CLASSES_APP_ID}
      - CLASSES_APP_KEY=${CLASSES_APP_KEY}
  frontend:
    build: frontend
    restart: always
    command: npm start
    volumes:
      - ./frontend:/code
      - /code/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
