version: '3'
services:
  db:
    image: postgres
  backend:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - LOCAL=1
  frontend:
    build: frontend
    command: npm start
    volumes:
      - ./frontend:/code
    ports:
      - "3000:3000"
    depends_on:
      - backend
