SUBJECTS = ["STUDIES", "AEROSPC", "AFRICAM", "ARESEC", "AMERSTD", "AHMA",
            "ANTHRO", "AST", "ARABIC", "ARCH", "ARMENI", "ART", "ASAMST",
            "ASIANST", "ASTRON", "BANGLA", "BIOENG", "BIOLOGY", "BIOPHY",
            "BOSCRSR", "BUDDSTD", "BURMESE", "MBA", "PHDBA", "UGBA", "CATALAN",
            "CELTIC", "CHMENG", "CHEM", "CHICANO", "CHINESE", "CYPLAN",
            "CIVENG", "CLASSIC", "COGSCI", "COLWRIT", "COMPBIO", "COMLIT",
            "CMPBIO", "COMPSCI", "CRITTH", "CUNEIF",  "CZECH", "DANISH",
            "DATASCI", "DEMOG", "DESINV", "DEVENG", "DEVP", "DEVSTD", "DUTCH",
            "EPS", "EALANG", "ECON",     "EDUC", "EGYPT", "EECS", "ELENG",
            "ENERES", "ENGIN", "ENGLISH", "ESPM", "ENVECON", "ENVDES", "ETHSTD",
            "EUST", "EWMBA", "XMBA", "XAFRICA", "XANTHRO", "XART", "XASAMST",
            "XASTRON", "XCLASSI", "XCOLWRI", "XCOMLIT", "XEPS", "XENGLIS",
            "XESPM", "XETHSTD", "XFILM", "XGWS", "XGEOG", "XHISTOR", 
            "XHISTAR", "XINTEGB", "XLEGALS", "XLS", "XLINGUI", "XMATH",
            "XMESTU", "XMCELLB", "XMUSIC", "XPHILOS", "XPOLSCI", "XPSYCH",
            "XRHETOR", "XSOCIOL", "XSTAT",  "FILIPN", "FILM", "MFE", "FINNISH",
            "FOLKLOR", "FRENCH", "GWS", "GEOG", "GERMAN", "GMS", "GPP", "GREEK",
            "HMEDSCI", "HEBREW", "HINURD", "HISTORY", "HISTART", "HUNGARI",
            "ICELAND", "INDENG", "INFO", "INTEGBI", "ISF", "IAS", "ITALIAN",
            "JAPAN", "JEWISH", "JOURN", "KHMER", "KOREAN", "LGBT", "LDARCH",
            "LANPRO", "LATIN", "LATAMST",   "LAW", "LEGALST", "LS", "LINGUIS",
            "MALAYI", "MATSCI", "MATH", "MECENG", "MEDIAST", "MEDST", "MESTU",
            "MILAFF", "MILSCI", "MCELLBI", "MONGOLN", "MUSIC", "NSE", "NATAMST",
            "NATRES", "NAVSCI", "NESTUD", "NEUROSC", "NWMEDIA", "NORWEGN",
            "NUCENG", "NUSCTX", "OPTOM", "PACS", "PERSIAN", "PHILOS", "PHYSED",
            "PHYSICS", "PLANTBI", "POLISH", "POLECON", "POLSCI", "PORTUG",
            "PSEUDO", "PSYCH", "PUBAFF", "PBHLTH", "PUBPOL", "PUNJABI",
            "RHETOR", "RUSSIAN", "SANSKR", "SCANDIN", "SCMATHE", "STS",
            "SEMITIC", "SLAVIC", "SOCWEL", "SOCIOL", "SSEASN", "SASIAN",
            "SEASIAN", "SPANISH", "STAT", "SWEDISH", "TAMIL", "TELUGU", "THAI",
            "THEATER", "TIBETAN", "TURKISH", "UGIS", "VIETNMS", "VISSCI",
            "VISSTD", "YIDDISH"]
