# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BerkeleyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=10000, unique=True)),
                ('term', models.IntegerField()),
                ('term_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('offering_number', models.IntegerField()),
                ('description', models.TextField(max_length=5000)),
                ('subject_code', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('enrolled_count', models.IntegerField()),
                ('waitlisted_count', models.IntegerField()),
                ('min_enroll', models.IntegerField()),
                ('max_enroll', models.IntegerField()),
                ('max_waitlist', models.IntegerField()),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('enrollment_status_code', models.CharField(default='', max_length=100, null=True)),
                ('enrollment_status', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
