# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20170730_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berkeleyclass',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='berkeleyclass',
            name='start_date',
        ),
        migrations.AddField(
            model_name='berkeleyclass',
            name='component',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='berkeleyclass',
            name='component_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='berkeleyclass',
            name='description',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='berkeleyclass',
            name='enrolled_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='berkeleyclass',
            name='max_enroll',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='berkeleyclass',
            name='max_waitlist',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='berkeleyclass',
            name='min_enroll',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='berkeleyclass',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='berkeleyclass',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='berkeleyclass',
            name='subject_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='berkeleyclass',
            name='term',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='berkeleyclass',
            name='term_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='berkeleyclass',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='berkeleyclass',
            name='waitlisted_count',
            field=models.IntegerField(default=0),
        ),
    ]
